namespace VDew.DomainDrivenDesign.Application.Commands
{
    /// <summary>
    /// Base class for the <see cref="ICommand"/> contract.
    /// </summary>
    public class CommandBase : ICommand
    {
        /// <summary>
        /// <inheritdoc/>
        /// </summary>
        public Guid CommandId { get; }

        /// <summary>
        /// Initialize a new instance of <see cref="CommandBase{TResult}"/> with an autogenerated value for <see cref="CommandId"/>.
        /// </summary>
        public CommandBase() => CommandId = Guid.NewGuid();

        /// <summary>
        /// Initialize a new instance of <see cref="CommandBase{TResult}"/> with the specified value for <see cref="CommandId"/>.
        /// </summary>
        /// <param name="commandId">Identifier of the command.</param>
        public CommandBase(Guid commandId) => CommandId = commandId;
    }

    /// <summary>
    /// Base class for the <see cref="ICommand{TResult}"/> contract.
    /// </summary>
    /// <typeparam name="TResult">Type of the command result.</typeparam>
    public abstract class CommandBase<TResult> : ICommand<TResult>
    {
        /// <summary>
        /// <inheritdoc/>
        /// </summary>
        public Guid CommandId { get; }

        /// <summary>
        /// Initialize a new instance of <see cref="CommandBase{TResult}"/> with an autogenerated value for <see cref="CommandId"/>.
        /// </summary>
        public CommandBase() => CommandId = Guid.NewGuid();

        /// <summary>
        /// Initialize a new instance of <see cref="CommandBase{TResult}"/> with the specified value for <see cref="CommandId"/>.
        /// </summary>
        /// <param name="commandId">Identifier of the command.</param>
        public CommandBase(Guid commandId) => CommandId = commandId;
    }
}
